# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dart-math',
                'doc_host': 'https://hkust-nlp.github.io',
                'git_url': 'https://github.com/hkust-nlp/dart-math',
                'lib_path': 'dart'},
  'syms': {'dart.core': {'dart.core.foo': ('core.html#foo', 'dart/core.py')}}}
